// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCnHvQ905Hnolbzmw6YM3rD11ZRybap48',
    appId: '1:799710342273:web:4dd6722ad5aab6bff3f180',
    messagingSenderId: '799710342273',
    projectId: 'brasiltoon-5983e',
    authDomain: 'brasiltoon-5983e.firebaseapp.com',
    storageBucket: 'brasiltoon-5983e.appspot.com',
    measurementId: 'G-7YM2E1EHB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8HSzQwpAKHOMdckA-cGVIKCyUu6Ce1hU',
    appId: '1:799710342273:android:e22fbd28f785fa10f3f180',
    messagingSenderId: '799710342273',
    projectId: 'brasiltoon-5983e',
    storageBucket: 'brasiltoon-5983e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZZKuuK07jDR3_Qysj6hBJ1bpmsZm_TJw',
    appId: '1:799710342273:ios:5d80c004a9ba2d73f3f180',
    messagingSenderId: '799710342273',
    projectId: 'brasiltoon-5983e',
    storageBucket: 'brasiltoon-5983e.appspot.com',
    iosBundleId: 'com.example.brasiltoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZZKuuK07jDR3_Qysj6hBJ1bpmsZm_TJw',
    appId: '1:799710342273:ios:3d25697b525b09d9f3f180',
    messagingSenderId: '799710342273',
    projectId: 'brasiltoon-5983e',
    storageBucket: 'brasiltoon-5983e.appspot.com',
    iosBundleId: 'com.example.brasiltoon.RunnerTests',
  );
}
